/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PartialRideId = IDL.Text;
export const AutoSaveRideRequest = IDL.Record({
  'id' : PartialRideId,
  'avgSpeed' : IDL.Float64,
  'avgResistance' : IDL.Nat,
  'calories' : IDL.Nat,
  'distanceKm' : IDL.Float64,
  'avgCadence' : IDL.Nat,
  'elapsedSeconds' : IDL.Nat,
  'startTimestamp' : IDL.Int,
  'avgHeartRate' : IDL.Nat,
});
export const PartialRide = IDL.Record({
  'id' : PartialRideId,
  'avgSpeed' : IDL.Float64,
  'avgResistance' : IDL.Nat,
  'calories' : IDL.Nat,
  'lastSavedAt' : IDL.Int,
  'distanceKm' : IDL.Float64,
  'avgCadence' : IDL.Nat,
  'elapsedSeconds' : IDL.Nat,
  'startTimestamp' : IDL.Int,
  'avgHeartRate' : IDL.Nat,
  'isPartial' : IDL.Bool,
});
export const RideId = IDL.Nat;
export const Time = IDL.Int;
export const Ride = IDL.Record({
  'id' : RideId,
  'peakResistance' : IDL.Nat,
  'avgResistance' : IDL.Float64,
  'maxHeartRate' : IDL.Opt(IDL.Nat),
  'date' : Time,
  'calories' : IDL.Float64,
  'durationSeconds' : IDL.Nat,
  'maxResistance' : IDL.Nat,
  'minResistance' : IDL.Nat,
  'hydrationLogged' : IDL.Opt(IDL.Nat),
  'distanceMeters' : IDL.Float64,
  'avgSpeedKph' : IDL.Float64,
  'avgHeartRate' : IDL.Opt(IDL.Nat),
});
export const StatsResult = IDL.Record({
  'avgSpeed' : IDL.Float64,
  'maxHeartRate' : IDL.Opt(IDL.Nat),
  'totalCalories' : IDL.Nat,
  'totalHydration' : IDL.Nat,
  'totalDurationSeconds' : IDL.Nat,
  'totalDistance' : IDL.Float64,
  'rides' : IDL.Vec(Ride),
  'avgHeartRate' : IDL.Opt(IDL.Nat),
  'totalRides' : IDL.Nat,
});
export const RideSummary = IDL.Record({
  'totalDistanceMeters' : IDL.Float64,
  'totalCalories' : IDL.Float64,
  'totalDurationSeconds' : IDL.Nat,
  'totalCaloriesNat' : IDL.Nat,
  'totalDistance' : IDL.Float64,
  'totalRides' : IDL.Nat,
});
export const SaveRideRequest = IDL.Record({
  'peakResistance' : IDL.Nat,
  'avgResistance' : IDL.Float64,
  'maxHeartRate' : IDL.Opt(IDL.Nat),
  'calories' : IDL.Float64,
  'durationSeconds' : IDL.Nat,
  'maxResistance' : IDL.Nat,
  'minResistance' : IDL.Nat,
  'hydrationLogged' : IDL.Opt(IDL.Nat),
  'distanceMeters' : IDL.Float64,
  'avgSpeedKph' : IDL.Float64,
  'avgHeartRate' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'autoSaveRide' : IDL.Func([AutoSaveRideRequest], [PartialRide], []),
  'clearPartialRide' : IDL.Func([IDL.Int, IDL.Int], [IDL.Bool], []),
  'deleteRide' : IDL.Func([RideId], [IDL.Bool], []),
  'getPartialRide' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Opt(PartialRide)],
      ['query'],
    ),
  'getRidesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Ride)],
      ['query'],
    ),
  'getStatsByPeriod' : IDL.Func([IDL.Int, IDL.Int], [StatsResult], ['query']),
  'getSummary' : IDL.Func([], [RideSummary], ['query']),
  'listRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'saveRide' : IDL.Func([SaveRideRequest], [Ride], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PartialRideId = IDL.Text;
  const AutoSaveRideRequest = IDL.Record({
    'id' : PartialRideId,
    'avgSpeed' : IDL.Float64,
    'avgResistance' : IDL.Nat,
    'calories' : IDL.Nat,
    'distanceKm' : IDL.Float64,
    'avgCadence' : IDL.Nat,
    'elapsedSeconds' : IDL.Nat,
    'startTimestamp' : IDL.Int,
    'avgHeartRate' : IDL.Nat,
  });
  const PartialRide = IDL.Record({
    'id' : PartialRideId,
    'avgSpeed' : IDL.Float64,
    'avgResistance' : IDL.Nat,
    'calories' : IDL.Nat,
    'lastSavedAt' : IDL.Int,
    'distanceKm' : IDL.Float64,
    'avgCadence' : IDL.Nat,
    'elapsedSeconds' : IDL.Nat,
    'startTimestamp' : IDL.Int,
    'avgHeartRate' : IDL.Nat,
    'isPartial' : IDL.Bool,
  });
  const RideId = IDL.Nat;
  const Time = IDL.Int;
  const Ride = IDL.Record({
    'id' : RideId,
    'peakResistance' : IDL.Nat,
    'avgResistance' : IDL.Float64,
    'maxHeartRate' : IDL.Opt(IDL.Nat),
    'date' : Time,
    'calories' : IDL.Float64,
    'durationSeconds' : IDL.Nat,
    'maxResistance' : IDL.Nat,
    'minResistance' : IDL.Nat,
    'hydrationLogged' : IDL.Opt(IDL.Nat),
    'distanceMeters' : IDL.Float64,
    'avgSpeedKph' : IDL.Float64,
    'avgHeartRate' : IDL.Opt(IDL.Nat),
  });
  const StatsResult = IDL.Record({
    'avgSpeed' : IDL.Float64,
    'maxHeartRate' : IDL.Opt(IDL.Nat),
    'totalCalories' : IDL.Nat,
    'totalHydration' : IDL.Nat,
    'totalDurationSeconds' : IDL.Nat,
    'totalDistance' : IDL.Float64,
    'rides' : IDL.Vec(Ride),
    'avgHeartRate' : IDL.Opt(IDL.Nat),
    'totalRides' : IDL.Nat,
  });
  const RideSummary = IDL.Record({
    'totalDistanceMeters' : IDL.Float64,
    'totalCalories' : IDL.Float64,
    'totalDurationSeconds' : IDL.Nat,
    'totalCaloriesNat' : IDL.Nat,
    'totalDistance' : IDL.Float64,
    'totalRides' : IDL.Nat,
  });
  const SaveRideRequest = IDL.Record({
    'peakResistance' : IDL.Nat,
    'avgResistance' : IDL.Float64,
    'maxHeartRate' : IDL.Opt(IDL.Nat),
    'calories' : IDL.Float64,
    'durationSeconds' : IDL.Nat,
    'maxResistance' : IDL.Nat,
    'minResistance' : IDL.Nat,
    'hydrationLogged' : IDL.Opt(IDL.Nat),
    'distanceMeters' : IDL.Float64,
    'avgSpeedKph' : IDL.Float64,
    'avgHeartRate' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'autoSaveRide' : IDL.Func([AutoSaveRideRequest], [PartialRide], []),
    'clearPartialRide' : IDL.Func([IDL.Int, IDL.Int], [IDL.Bool], []),
    'deleteRide' : IDL.Func([RideId], [IDL.Bool], []),
    'getPartialRide' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Opt(PartialRide)],
        ['query'],
      ),
    'getRidesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Ride)],
        ['query'],
      ),
    'getStatsByPeriod' : IDL.Func([IDL.Int, IDL.Int], [StatsResult], ['query']),
    'getSummary' : IDL.Func([], [RideSummary], ['query']),
    'listRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'saveRide' : IDL.Func([SaveRideRequest], [Ride], []),
  });
};

export const init = ({ IDL }) => { return []; };