/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutoSaveRideRequest {
  'id' : PartialRideId,
  'avgSpeed' : number,
  'avgResistance' : bigint,
  'calories' : bigint,
  'distanceKm' : number,
  'avgCadence' : bigint,
  'elapsedSeconds' : bigint,
  'startTimestamp' : bigint,
  'avgHeartRate' : bigint,
}
export interface PartialRide {
  'id' : PartialRideId,
  'avgSpeed' : number,
  'avgResistance' : bigint,
  'calories' : bigint,
  'lastSavedAt' : bigint,
  'distanceKm' : number,
  'avgCadence' : bigint,
  'elapsedSeconds' : bigint,
  'startTimestamp' : bigint,
  'avgHeartRate' : bigint,
  'isPartial' : boolean,
}
export type PartialRideId = string;
export interface Ride {
  'id' : RideId,
  'peakResistance' : bigint,
  'avgResistance' : number,
  'maxHeartRate' : [] | [bigint],
  'date' : Time,
  'calories' : number,
  'durationSeconds' : bigint,
  'maxResistance' : bigint,
  'minResistance' : bigint,
  'hydrationLogged' : [] | [bigint],
  'distanceMeters' : number,
  'avgSpeedKph' : number,
  'avgHeartRate' : [] | [bigint],
}
export type RideId = bigint;
export interface RideSummary {
  'totalDistanceMeters' : number,
  'totalCalories' : number,
  'totalDurationSeconds' : bigint,
  'totalCaloriesNat' : bigint,
  'totalDistance' : number,
  'totalRides' : bigint,
}
export interface SaveRideRequest {
  'peakResistance' : bigint,
  'avgResistance' : number,
  'maxHeartRate' : [] | [bigint],
  'calories' : number,
  'durationSeconds' : bigint,
  'maxResistance' : bigint,
  'minResistance' : bigint,
  'hydrationLogged' : [] | [bigint],
  'distanceMeters' : number,
  'avgSpeedKph' : number,
  'avgHeartRate' : [] | [bigint],
}
export interface StatsResult {
  'avgSpeed' : number,
  'maxHeartRate' : [] | [bigint],
  'totalCalories' : bigint,
  'totalHydration' : bigint,
  'totalDurationSeconds' : bigint,
  'totalDistance' : number,
  'rides' : Array<Ride>,
  'avgHeartRate' : [] | [bigint],
  'totalRides' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'autoSaveRide' : ActorMethod<[AutoSaveRideRequest], PartialRide>,
  'clearPartialRide' : ActorMethod<[bigint, bigint], boolean>,
  'deleteRide' : ActorMethod<[RideId], boolean>,
  'getPartialRide' : ActorMethod<[bigint, bigint], [] | [PartialRide]>,
  'getRidesByDateRange' : ActorMethod<[bigint, bigint], Array<Ride>>,
  'getStatsByPeriod' : ActorMethod<[bigint, bigint], StatsResult>,
  'getSummary' : ActorMethod<[], RideSummary>,
  'listRides' : ActorMethod<[], Array<Ride>>,
  'saveRide' : ActorMethod<[SaveRideRequest], Ride>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];