/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PartialRideId = string;
export interface AutoSaveRideRequest {
    id: PartialRideId;
    avgSpeed: number;
    avgResistance: bigint;
    calories: bigint;
    distanceKm: number;
    avgCadence: bigint;
    elapsedSeconds: bigint;
    startTimestamp: bigint;
    avgHeartRate: bigint;
}
export type Time = bigint;
export interface Ride {
    id: RideId;
    peakResistance: bigint;
    avgResistance: number;
    maxHeartRate?: bigint;
    date: Time;
    calories: number;
    durationSeconds: bigint;
    maxResistance: bigint;
    minResistance: bigint;
    hydrationLogged?: bigint;
    distanceMeters: number;
    avgSpeedKph: number;
    avgHeartRate?: bigint;
}
export interface StatsResult {
    avgSpeed: number;
    maxHeartRate?: bigint;
    totalCalories: bigint;
    totalHydration: bigint;
    totalDurationSeconds: bigint;
    totalDistance: number;
    rides: Array<Ride>;
    avgHeartRate?: bigint;
    totalRides: bigint;
}
export interface SaveRideRequest {
    peakResistance: bigint;
    avgResistance: number;
    maxHeartRate?: bigint;
    calories: number;
    durationSeconds: bigint;
    maxResistance: bigint;
    minResistance: bigint;
    hydrationLogged?: bigint;
    distanceMeters: number;
    avgSpeedKph: number;
    avgHeartRate?: bigint;
}
export interface RideSummary {
    totalDistanceMeters: number;
    totalCalories: number;
    totalDurationSeconds: bigint;
    totalCaloriesNat: bigint;
    totalDistance: number;
    totalRides: bigint;
}
export type RideId = bigint;
export interface PartialRide {
    id: PartialRideId;
    avgSpeed: number;
    avgResistance: bigint;
    calories: bigint;
    lastSavedAt: bigint;
    distanceKm: number;
    avgCadence: bigint;
    elapsedSeconds: bigint;
    startTimestamp: bigint;
    avgHeartRate: bigint;
    isPartial: boolean;
}
export interface backendInterface {
    autoSaveRide(req: AutoSaveRideRequest): Promise<PartialRide>;
    clearPartialRide(dayStartMs: bigint, dayEndMs: bigint): Promise<boolean>;
    deleteRide(id: RideId): Promise<boolean>;
    getPartialRide(dayStartMs: bigint, dayEndMs: bigint): Promise<PartialRide | null>;
    getRidesByDateRange(startMs: bigint, endMs: bigint): Promise<Array<Ride>>;
    getStatsByPeriod(startMs: bigint, endMs: bigint): Promise<StatsResult>;
    getSummary(): Promise<RideSummary>;
    listRides(): Promise<Array<Ride>>;
    saveRide(req: SaveRideRequest): Promise<Ride>;
}
import type { PartialRide as _PartialRide, Ride as _Ride, RideId as _RideId, SaveRideRequest as _SaveRideRequest, StatsResult as _StatsResult, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async autoSaveRide(arg0: AutoSaveRideRequest): Promise<PartialRide> {
        if (this.processError) {
            try {
                const result = await this.actor.autoSaveRide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoSaveRide(arg0);
            return result;
        }
    }
    async clearPartialRide(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPartialRide(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPartialRide(arg0, arg1);
            return result;
        }
    }
    async deleteRide(arg0: RideId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRide(arg0);
            return result;
        }
    }
    async getPartialRide(arg0: bigint, arg1: bigint): Promise<PartialRide | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartialRide(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartialRide(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRidesByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Ride>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRidesByDateRange(arg0, arg1);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRidesByDateRange(arg0, arg1);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatsByPeriod(arg0: bigint, arg1: bigint): Promise<StatsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatsByPeriod(arg0, arg1);
                return from_candid_StatsResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatsByPeriod(arg0, arg1);
            return from_candid_StatsResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummary(): Promise<RideSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummary();
            return result;
        }
    }
    async listRides(): Promise<Array<Ride>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRides();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRides();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveRide(arg0: SaveRideRequest): Promise<Ride> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRide(to_candid_SaveRideRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Ride_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRide(to_candid_SaveRideRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Ride_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Ride_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ride): Ride {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_StatsResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatsResult): StatsResult {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartialRide]): PartialRide | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RideId;
    peakResistance: bigint;
    avgResistance: number;
    maxHeartRate: [] | [bigint];
    date: _Time;
    calories: number;
    durationSeconds: bigint;
    maxResistance: bigint;
    minResistance: bigint;
    hydrationLogged: [] | [bigint];
    distanceMeters: number;
    avgSpeedKph: number;
    avgHeartRate: [] | [bigint];
}): {
    id: RideId;
    peakResistance: bigint;
    avgResistance: number;
    maxHeartRate?: bigint;
    date: Time;
    calories: number;
    durationSeconds: bigint;
    maxResistance: bigint;
    minResistance: bigint;
    hydrationLogged?: bigint;
    distanceMeters: number;
    avgSpeedKph: number;
    avgHeartRate?: bigint;
} {
    return {
        id: value.id,
        peakResistance: value.peakResistance,
        avgResistance: value.avgResistance,
        maxHeartRate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.maxHeartRate)),
        date: value.date,
        calories: value.calories,
        durationSeconds: value.durationSeconds,
        maxResistance: value.maxResistance,
        minResistance: value.minResistance,
        hydrationLogged: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.hydrationLogged)),
        distanceMeters: value.distanceMeters,
        avgSpeedKph: value.avgSpeedKph,
        avgHeartRate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.avgHeartRate))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avgSpeed: number;
    maxHeartRate: [] | [bigint];
    totalCalories: bigint;
    totalHydration: bigint;
    totalDurationSeconds: bigint;
    totalDistance: number;
    rides: Array<_Ride>;
    avgHeartRate: [] | [bigint];
    totalRides: bigint;
}): {
    avgSpeed: number;
    maxHeartRate?: bigint;
    totalCalories: bigint;
    totalHydration: bigint;
    totalDurationSeconds: bigint;
    totalDistance: number;
    rides: Array<Ride>;
    avgHeartRate?: bigint;
    totalRides: bigint;
} {
    return {
        avgSpeed: value.avgSpeed,
        maxHeartRate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.maxHeartRate)),
        totalCalories: value.totalCalories,
        totalHydration: value.totalHydration,
        totalDurationSeconds: value.totalDurationSeconds,
        totalDistance: value.totalDistance,
        rides: from_candid_vec_n2(_uploadFile, _downloadFile, value.rides),
        avgHeartRate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.avgHeartRate)),
        totalRides: value.totalRides
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ride>): Array<Ride> {
    return value.map((x)=>from_candid_Ride_n3(_uploadFile, _downloadFile, x));
}
function to_candid_SaveRideRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveRideRequest): _SaveRideRequest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    peakResistance: bigint;
    avgResistance: number;
    maxHeartRate?: bigint;
    calories: number;
    durationSeconds: bigint;
    maxResistance: bigint;
    minResistance: bigint;
    hydrationLogged?: bigint;
    distanceMeters: number;
    avgSpeedKph: number;
    avgHeartRate?: bigint;
}): {
    peakResistance: bigint;
    avgResistance: number;
    maxHeartRate: [] | [bigint];
    calories: number;
    durationSeconds: bigint;
    maxResistance: bigint;
    minResistance: bigint;
    hydrationLogged: [] | [bigint];
    distanceMeters: number;
    avgSpeedKph: number;
    avgHeartRate: [] | [bigint];
} {
    return {
        peakResistance: value.peakResistance,
        avgResistance: value.avgResistance,
        maxHeartRate: value.maxHeartRate ? candid_some(value.maxHeartRate) : candid_none(),
        calories: value.calories,
        durationSeconds: value.durationSeconds,
        maxResistance: value.maxResistance,
        minResistance: value.minResistance,
        hydrationLogged: value.hydrationLogged ? candid_some(value.hydrationLogged) : candid_none(),
        distanceMeters: value.distanceMeters,
        avgSpeedKph: value.avgSpeedKph,
        avgHeartRate: value.avgHeartRate ? candid_some(value.avgHeartRate) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
